{% set name = "psy-maps" %}
{% set version = "1.1.0" %}
{% set sha256 = "9b1d7ad733226efd0f5bb556e067210030537de4f51a61bdce4bd2b1e9686afb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
  - python
  - setuptools
  run:
  - python
  - psyplot
  - psy-simple
  - cartopy

test:
  imports:
  - psy_maps

about:
  home: https://github.com/Chilipp/psy-maps
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: http://psyplot.readthedocs.io/projects/psy-maps
  dev_url: https://github.com/Chilipp/psy-maps

extra:
  recipe-maintainers:
    - Chilipp
